# Generated by Django 3.2.6 on 2022-10-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercreationApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercreate',
            name='phonenumber',
            field=models.IntegerField(),
        ),
    ]
